# Generated by Django 3.0.4 on 2020-04-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soliloquy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='references',
        ),
        migrations.AlterField(
            model_name='reference',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='soliloquy.Entry'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='soliloquy.Entry'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
