# Generated by Django 3.0.4 on 2020-04-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soliloquy', '0002_auto_20200425_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
