# Generated by Django 3.0.4 on 2020-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soliloquy', '0003_auto_20200425_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
