# Generated by Django 3.0.4 on 2020-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soliloquy', '0004_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
