# Generated by Django 3.0.4 on 2020-07-06 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soliloquy', '0006_auto_20200611_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='parent_notebook',
        ),
        migrations.AddField(
            model_name='note',
            name='parent_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_notes', to='soliloquy.Note'),
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
