# Generated by Django 3.1.3 on 2020-11-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soliloquy', '0010_auto_20201116_1839'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='client_composite_key_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='entry',
            name='entry_composite_key_constraint',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='client',
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soliloquy.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
