# Generated by Django 3.1.3 on 2020-11-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soliloquy', '0011_auto_20201122_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
